-- ════════════════════════════════════════════════════════════
-- SpinLog — gemini_keys
-- Encrypted backup of Sage's Gemini API key ring.
--
-- Run this once in the Supabase SQL editor:
--   Dashboard → SQL Editor → New query → paste → Run
--
-- ── READ THIS BEFORE USING IT ────────────────────────────────
-- This project talks to Supabase with the anon key, and that key is in the
-- JavaScript the browser downloads. Anyone who opens devtools on this app
-- can therefore read any table the anon role can read — and every policy
-- here is `using (true)`, because there is no login to key them off.
--
-- A Gemini API key is a billable credential. Storing one in plain text in
-- this table would be the same as publishing it.
--
-- So nothing in this table is plaintext. The app encrypts each key in the
-- browser with AES-256-GCM, using a key derived by PBKDF2 from a passphrase
-- you choose. The passphrase is never sent to Supabase, never stored in any
-- column here, and cannot be recovered from anything in this table.
--
-- What someone with the anon key can therefore learn:
--   · how many keys you have
--   · the masked label of each (e.g. "AIza••••••rKRw") — already non-secret
--   · a ciphertext they cannot read without your passphrase
--
-- Two consequences worth being clear about:
--   · Lose the passphrase and the backup is gone. There is no reset. That is
--     what makes it safe, not an oversight.
--   · If you would rather not store keys off-device at all, simply do not run
--     this file. The app works exactly as before — keys stay in localStorage,
--     and the Backup panel says it is not set up.
--
-- Safe to run more than once. Every statement is guarded.
-- ════════════════════════════════════════════════════════════


-- ── 0. Adopt the table created by hand in the dashboard ──────────────
-- The Table Editor names a new table exactly as typed, so "Gemini Api keys"
-- arrives with capitals and spaces and has to be quoted forever after.
-- Renaming it once brings it in line with the other tables. The two columns
-- it already has (id, created_at) are the two this schema wants anyway.
do $$
begin
  if exists (
        select 1 from information_schema.tables
        where table_schema = 'public' and table_name = 'Gemini Api keys')
     and not exists (
        select 1 from information_schema.tables
        where table_schema = 'public' and table_name = 'gemini_keys')
  then
    alter table public."Gemini Api keys" rename to gemini_keys;
    raise notice 'Renamed "Gemini Api keys" to gemini_keys.';
  end if;
end $$;


-- ── 1. The table ─────────────────────────────────────────────────────
create table if not exists public.gemini_keys (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now()
);

-- Added one at a time so this works on a brand new table and on the
-- two-column one from the dashboard alike.
alter table public.gemini_keys add column if not exists key_id     text;
alter table public.gemini_keys add column if not exists label      text;
alter table public.gemini_keys add column if not exists cipher     text;
alter table public.gemini_keys add column if not exists iv         text;
alter table public.gemini_keys add column if not exists salt       text;
alter table public.gemini_keys add column if not exists device_id  text;
alter table public.gemini_keys add column if not exists added_at   timestamptz;
alter table public.gemini_keys add column if not exists updated_at timestamptz not null default now();

comment on table public.gemini_keys is
  'Encrypted backup of the Gemini API key ring. Every row is AES-256-GCM ciphertext; the passphrase that decrypts it never leaves the browser and is not stored in this database.';
comment on column public.gemini_keys.key_id is
  'Stable non-secret fingerprint of the key, used to match rows across devices. Not derived from the secret in a reversible way.';
comment on column public.gemini_keys.label is
  'Masked form shown in the UI, e.g. AIza******rKRw. Deliberately non-secret — it is what the settings screen already displays.';
comment on column public.gemini_keys.cipher is
  'The API key, AES-256-GCM encrypted, base64. Useless without the passphrase. This is the only place key material exists in this table.';
comment on column public.gemini_keys.iv is
  'Per-row random initialisation vector, base64. Not secret, and must never be reused for two encryptions under the same derived key.';
comment on column public.gemini_keys.salt is
  'PBKDF2 salt for the whole vault, base64. Not secret. Identical on every row so any single row can bootstrap the key derivation.';


-- ── 2. Indexes ───────────────────────────────────────────────────────
-- key_id is how the app finds a row to update, so it is unique. Postgres
-- allows repeated nulls in a unique index, which is what lets the column be
-- added to an existing table without a backfill.
create unique index if not exists gemini_keys_key_id_idx
  on public.gemini_keys (key_id);


-- ── 3. Keep updated_at honest ────────────────────────────────────────
create or replace function public.gemini_keys_touch()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end $$;

drop trigger if exists gemini_keys_touch_trg on public.gemini_keys;
create trigger gemini_keys_touch_trg
  before update on public.gemini_keys
  for each row execute function public.gemini_keys_touch();


-- ── 4. Row level security ────────────────────────────────────────────
-- Anon, like every other table here. The confidentiality of these rows comes
-- from the encryption, not from these policies — see the header.
alter table public.gemini_keys enable row level security;

drop policy if exists "gemini_keys anon read"   on public.gemini_keys;
drop policy if exists "gemini_keys anon insert" on public.gemini_keys;
drop policy if exists "gemini_keys anon update" on public.gemini_keys;
drop policy if exists "gemini_keys anon delete" on public.gemini_keys;

create policy "gemini_keys anon read"
  on public.gemini_keys for select using (true);

create policy "gemini_keys anon insert"
  on public.gemini_keys for insert with check (true);

create policy "gemini_keys anon update"
  on public.gemini_keys for update using (true) with check (true);

create policy "gemini_keys anon delete"
  on public.gemini_keys for delete using (true);


-- ── 5. A view that cannot leak the ciphertext ────────────────────────
-- For looking at the ring in the dashboard without the encrypted blobs in the
-- way. security_invoker so it obeys the caller's RLS rather than the owner's.
create or replace view public.gemini_keys_list
  with (security_invoker = true)
as
select
  id,
  key_id,
  label        as masked_key,
  device_id    as added_from,
  added_at,
  updated_at
from public.gemini_keys
where cipher is not null
order by added_at nulls last, id;

comment on view public.gemini_keys_list is
  'The key ring without the ciphertext: how many keys there are and their masked labels. Safe to read casually.';
