-- ════════════════════════════════════════════════════════════
-- SpinLog — park_locations
-- Where the bike was left, in a table of its own.
--
-- Run this once in the Supabase SQL editor:
--   Dashboard → SQL Editor → New query → paste → Run
--
-- Until it is run the app keeps reading park spots out of sage_memory exactly as
-- it did before, so nothing breaks in the meantime. Once it is run, the spots move
-- across, the old rows are removed, and parking gets the columns it always wanted.
--
-- Safe to run more than once. Every statement is guarded.
--
--
-- ── WHY A TABLE, AFTER cloud_routing.sql ARGUED FOR THE OPPOSITE ──
--
-- That file put park spots into sage_memory as `record_type = 'park'`, and its
-- reasoning was sound at the time: one table, one RLS set, one migration, and a
-- parked spot is three numbers and a string.
--
-- It stopped being sound the moment parking grew. A spot now wants a label, a
-- level, a note, a photo, and a time limit it can be reminded about. In
-- sage_memory that is six more keys stuffed into the `data` jsonb, unqueryable and
-- untyped, on a table whose name says it holds something else. The comment in
-- cloud-store.js says "NO NEW TABLES, and that shaped the design rather than being
-- a constraint worked around" — which was true, and the honest follow-up is that
-- the shape it produced no longer fits.
--
-- What actually changes:
--   · `until` is a real timestamptz that can be indexed and compared, not a
--     string in a jsonb blob
--   · a park write stops carrying weight/confidence/pinned/hits/rev, five columns
--     it only ever sent to satisfy sage_memory's NOT NULL defaults
--   · sage_memory goes back to being Sage's memory plus the conversation
--
--
-- ── ON THE NAME ──
--
-- The Table Editor was used to create a table called "Location" — capital L, which
-- Postgres folds into a quoted identifier, so it would need quoting in every
-- statement forever and `from('Location')` spelled exactly right in JS. It would be
-- the only quoted name in the project.
--
-- sage_memory.sql has a section 0 that exists for precisely this: it renamed a
-- dashboard-created "Sage Memory" to sage_memory so the app could use an unquoted
-- name. Section 0 below does the same thing, for the same reason, and the two
-- columns "Location" already has (id, created_at) are the two this schema wants
-- anyway, so nothing is lost.
--
-- `park_locations` rather than `locations`: this table is not every location the
-- app might ever know, it is where the bike was parked.
-- ════════════════════════════════════════════════════════════


-- ── 0. Adopt the table created by hand in the dashboard ──────────────
do $$
begin
  if exists (
        select 1 from information_schema.tables
        where table_schema = 'public' and table_name = 'Location')
     and not exists (
        select 1 from information_schema.tables
        where table_schema = 'public' and table_name = 'park_locations')
  then
    alter table public."Location" rename to park_locations;
    raise notice 'Renamed "Location" to park_locations.';
  end if;
end $$;


-- ── 1. The table ─────────────────────────────────────────────────────
-- One row per saved spot. The app keeps the newest few and deletes the rest, in
-- the cloud as well as on screen, so this does not grow without bound.
create table if not exists public.park_locations (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now()
);

-- Added one at a time so this works on a brand new table and on the two-column one
-- from the dashboard alike.

-- WHEN THE BIKE WAS LEFT. Not created_at: a spot saved on the phone and synced
-- later has two different times, and every read here is ordered by the first one.
-- This is also the row's client-stable identity — see the unique index below.
alter table public.park_locations add column if not exists parked_at   timestamptz;

alter table public.park_locations add column if not exists lat         double precision;
alter table public.park_locations add column if not exists lng         double precision;
-- Metres. What the device claimed, not what it achieved.
alter table public.park_locations add column if not exists accuracy_m  double precision;
-- Reverse-geocoded street and area. Arrives after the coordinates do, so it is
-- written by a second update and is null in between.
alter table public.park_locations add column if not exists address     text;

-- ── The advanced part ──
-- A car park is not a street address. "Phoenix Mall" plus "P2, row C" is how
-- somebody actually finds a bike again, and neither is derivable from coordinates
-- that are ±15m and indoors.
alter table public.park_locations add column if not exists label       text;
alter table public.park_locations add column if not exists level       text;
alter table public.park_locations add column if not exists notes       text;
-- A path in the media bucket. A photo of the pillar number beats any text.
alter table public.park_locations add column if not exists photo_path  text;

-- WHEN IT HAS TO BE MOVED BY. A real timestamptz so it can be compared and
-- indexed, which is the whole reason this is not a jsonb key: the reminder needs
-- "which spots are due in the next half hour", and that is a query.
alter table public.park_locations add column if not exists until       timestamptz;
-- So a reminder fires once rather than on every check.
alter table public.park_locations add column if not exists reminded_at timestamptz;

-- Which device saved it, matching the other tables. Useful when the laptop and the
-- phone disagree about where the bike is.
alter table public.park_locations add column if not exists device_id   text;
alter table public.park_locations add column if not exists updated_at  timestamptz not null default now();

comment on table public.park_locations is
  'Where the bike was parked. One row per saved spot, newest kept. Moved out of '
  'sage_memory (record_type = ''park'') once a spot needed a label, a level, a '
  'photo and a time limit — six more keys in a jsonb blob on a table named after '
  'something else was the wrong shape. See supabase/park_locations.sql.';
comment on column public.park_locations.parked_at is
  'When the bike was left. The row''s stable identity — the app matches on this, '
  'not on id, so a spot edited from another device updates rather than duplicates. '
  'Distinct from created_at, which is when the row reached the database.';
comment on column public.park_locations.accuracy_m is
  'Radius in metres the device reported. Displayed as ±Nm; never used to reject a '
  'fix, because a bad fix plus a photo still finds the bike.';
comment on column public.park_locations.address is
  'Reverse-geocoded by the client after the spot is saved, so it is null for a '
  'moment and stays null when the geocoder is unreachable.';
comment on column public.park_locations.label is
  'What the rider calls the place — "Phoenix Mall", "office basement". Not derived '
  'from the coordinates.';
comment on column public.park_locations.level is
  'Floor, bay or pillar. The part of a car park no coordinate can express.';
comment on column public.park_locations.until is
  'When the bike has to be moved by — a meter, a two-hour bay, a tow zone. '
  'Indexed, because the reminder asks which spots are due soon.';
comment on column public.park_locations.reminded_at is
  'Set when the time-limit reminder has been sent, so it fires once.';


-- ── 2. Indexes ───────────────────────────────────────────────────────
-- parked_at is how the app identifies a row to update or delete, so it is unique.
-- Postgres allows repeated nulls in a unique index, which is what lets the column
-- be added to an existing table without a backfill.
create unique index if not exists park_locations_parked_at_idx
  on public.park_locations (parked_at);

-- The read the app actually makes: newest first.
create index if not exists park_locations_recent_idx
  on public.park_locations (parked_at desc);

-- "What is due soon", for the time-limit reminder. Partial, because a spot with no
-- limit and a spot already reminded about are both irrelevant to that question and
-- together they are most of the table.
create index if not exists park_locations_due_idx
  on public.park_locations (until)
  where until is not null and reminded_at is null;


-- ── 3. Keep updated_at honest ────────────────────────────────────────
-- The app sets updated_at on every write, but a row edited from the SQL editor or
-- the Table Editor would otherwise keep a stale value.
create or replace function public.park_locations_touch()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end $$;

drop trigger if exists park_locations_touch_trg on public.park_locations;
create trigger park_locations_touch_trg
  before update on public.park_locations
  for each row execute function public.park_locations_touch();


-- ── 4. Row level security ────────────────────────────────────────────
-- This project uses the anon key with no auth, matching the other tables.
--
-- DELETE matters more here than anywhere else in the app. Without the policy a
-- delete affects zero rows and returns NO ERROR: "forget this spot" would empty
-- the screen, report success, and the row would be back on the next load. The app
-- also trims past its keep limit with a delete, so without this the table grows
-- for ever while appearing not to.
alter table public.park_locations enable row level security;

drop policy if exists "park_locations anon read"   on public.park_locations;
drop policy if exists "park_locations anon insert" on public.park_locations;
drop policy if exists "park_locations anon update" on public.park_locations;
drop policy if exists "park_locations anon delete" on public.park_locations;

create policy "park_locations anon read"
  on public.park_locations for select using (true);

create policy "park_locations anon insert"
  on public.park_locations for insert with check (true);

create policy "park_locations anon update"
  on public.park_locations for update using (true) with check (true);

create policy "park_locations anon delete"
  on public.park_locations for delete using (true);


-- ── 5. Bring the existing spots across ───────────────────────────────
-- Copy first, delete second, and only delete what was actually copied — so an
-- interrupted run loses nothing and a second run is a no-op.
--
-- The old shape: content = address, data = { lat, lng, accuracy },
-- learned_at = when it was parked, mem_key = 'park:<ISO>'.
do $$
declare
  moved integer := 0;
  cleared integer := 0;
begin
  if not exists (
    select 1 from information_schema.tables
    where table_schema = 'public' and table_name = 'sage_memory'
  ) then
    raise notice 'No sage_memory table, so there is nothing to move.';
    return;
  end if;

  insert into public.park_locations
    (parked_at, lat, lng, accuracy_m, address,
     label, level, notes, photo_path, until, reminded_at,
     device_id, created_at, updated_at)
  select
    coalesce(m.learned_at, m.created_at),
    (m.data->>'lat')::double precision,
    (m.data->>'lng')::double precision,
    nullif(m.data->>'accuracy', '')::double precision,
    nullif(m.content, ''),
    -- The app writes these into `data` while this table does not exist yet, so a
    -- label or a time limit typed before the migration survives it.
    nullif(m.data->>'label', ''),
    nullif(m.data->>'level', ''),
    nullif(m.data->>'notes', ''),
    nullif(m.data->>'photo', ''),
    nullif(m.data->>'until', '')::timestamptz,
    nullif(m.data->>'remindedAt', '')::timestamptz,
    m.device_id,
    coalesce(m.created_at, now()),
    now()
  from public.sage_memory m
  where m.record_type = 'park'
    and m.data ? 'lat'
    and (m.data->>'lat') is not null
    and coalesce(m.learned_at, m.created_at) is not null
  -- parked_at is unique, so a spot already moved is skipped rather than duplicated.
  on conflict (parked_at) do nothing;

  get diagnostics moved = row_count;

  -- Only rows whose timestamp is now present in the new table. A row that failed
  -- the WHERE above — no coordinates, no timestamp — is left where it is rather
  -- than silently destroyed.
  delete from public.sage_memory m
   where m.record_type = 'park'
     and exists (
       select 1 from public.park_locations p
        where p.parked_at = coalesce(m.learned_at, m.created_at)
     );

  get diagnostics cleared = row_count;
  raise notice 'Moved % park spot(s) into park_locations and cleared % old row(s).', moved, cleared;
end $$;


-- ── 6. sage_memory no longer holds park spots ────────────────────────
-- Its comments still said it did, and a comment that lies is worse than none.
do $$
begin
  if exists (
    select 1 from information_schema.tables
    where table_schema = 'public' and table_name = 'sage_memory'
  ) then
    execute $c$comment on table public.sage_memory is
      'Sync log, NOT a list of memories. Six record types share it. fact / recap / '
      'relationship / episode are Sage''''s own memory — see the sage_memory_facts '
      'view. message / setting are app data routed through the same sync so the '
      'phone and the laptop agree — see the sage_conversation view. Park spots used '
      'to live here as record_type = ''''park'''' and now have their own table, '
      'park_locations. One chat exchange writes two message rows and updates the '
      'relationship row WITHOUT creating a memory, which is normal.'$c$;
    execute $c$comment on column public.sage_memory.record_type is
      'fact | recap | relationship | episode (hers) — message | setting (the '
      'app''''s). ''''park'''' was retired to public.park_locations.'$c$;
  end if;
end $$;


-- ── Check it worked ──
-- select count(*) as spots from public.park_locations;
-- select parked_at, label, level, address, accuracy_m, until
--   from public.park_locations order by parked_at desc;
-- select count(*) as leftover_park_rows from public.sage_memory where record_type = 'park';
-- select policyname from pg_policies where tablename = 'park_locations';
