-- ════════════════════════════════════════════════════════════
-- SpinLog — sage_memory
-- Sage's memory bank, moved off the device and into the database.
--
-- Run this once in the Supabase SQL editor:
--   Dashboard → SQL Editor → New query → paste → Run
--
-- Until it is run, Sage keeps everything in localStorage exactly as she did
-- before, so nothing breaks in the meantime. Once it is run, her memory
-- follows the account rather than the browser: clear site data, switch
-- phones, reinstall the PWA — she still knows him.
--
-- Safe to run more than once. Every statement is guarded.
--
-- ── WHAT YOU WILL SEE IN THE TABLE EDITOR ──
-- This table holds FOUR kinds of row, told apart by record_type, so the row
-- count is not the memory count. With one memory saved you will see two rows:
--
--   fact          one per thing she remembers      ← these are the memories
--   relationship  exactly one row, ever, updated in place on every message
--   recap         at most one row, her rolling note on older conversations
--   episode       one per finished conversation, for the timeline
--
-- To see only the memories, open the sage_memory_facts view created at the
-- bottom of this file. sage_memory_summary shows the makeup at a glance.
-- ════════════════════════════════════════════════════════════


-- ── 0. Adopt the table created by hand in the dashboard ──────────────
-- The Table Editor names a new table exactly as typed, so "Sage Memory"
-- arrives with a capital and a space and has to be quoted forever after.
-- Renaming it once brings it in line with maintenance_records,
-- vehicle_documents, media_files and vehicle_cover, and means the app can
-- use an unquoted name. The two columns it already has (id, created_at)
-- are the two this schema wants anyway, so nothing is lost.
do $$
begin
  if exists (
        select 1 from information_schema.tables
        where table_schema = 'public' and table_name = 'Sage Memory')
     and not exists (
        select 1 from information_schema.tables
        where table_schema = 'public' and table_name = 'sage_memory')
  then
    alter table public."Sage Memory" rename to sage_memory;
    raise notice 'Renamed "Sage Memory" to sage_memory.';
  end if;
end $$;


-- ── 1. The table ─────────────────────────────────────────────────────
-- One table, four kinds of row, told apart by record_type:
--
--   fact         one thing she knows about him
--   recap        her rolling note on conversations past her window (one row)
--   relationship how long they have known each other, counters (one row)
--   episode      a closed conversation, kept as a timeline entry
--
-- One table rather than four because they are written and synced together,
-- and a single RLS set is one thing to get right instead of four.
create table if not exists public.sage_memory (
  id            bigint generated by default as identity primary key,
  created_at    timestamptz not null default now()
);

-- Added one at a time so this works on a brand new table and on the
-- two-column one from the dashboard alike.
alter table public.sage_memory add column if not exists mem_key       text;
alter table public.sage_memory add column if not exists record_type   text    not null default 'fact';
alter table public.sage_memory add column if not exists device_id     text;
alter table public.sage_memory add column if not exists content       text;
alter table public.sage_memory add column if not exists kind          text;
alter table public.sage_memory add column if not exists topic         text;
alter table public.sage_memory add column if not exists source        text;
alter table public.sage_memory add column if not exists weight        real    not null default 1;
alter table public.sage_memory add column if not exists confidence    real    not null default 1;
alter table public.sage_memory add column if not exists pinned        boolean not null default false;
alter table public.sage_memory add column if not exists hits          integer not null default 0;
alter table public.sage_memory add column if not exists learned_at    timestamptz;
alter table public.sage_memory add column if not exists last_seen_at  timestamptz;
alter table public.sage_memory add column if not exists expires_at    timestamptz;
alter table public.sage_memory add column if not exists superseded_by text;
alter table public.sage_memory add column if not exists archived_at   timestamptz;
alter table public.sage_memory add column if not exists data          jsonb;
alter table public.sage_memory add column if not exists rev           integer not null default 1;
alter table public.sage_memory add column if not exists updated_at    timestamptz not null default now();

-- A note on the `not null default` columns above (record_type, weight,
-- confidence, pinned, hits, rev, updated_at).
--
-- The defaults only apply when a column is absent from the INSERT entirely.
-- PostgREST builds a multi-row insert from the UNION of the keys across all the
-- rows in the batch and writes NULL for any row missing one — so if a single
-- record type in a batch omits `weight`, that row arrives as NULL and Postgres
-- rejects the whole push with
--   null value in column "weight" ... violates not-null constraint
--
-- The client therefore sends every column on every row, whatever its type
-- (see baseRow() in src/js/sage-memory.js). Keep it that way when adding a
-- column here: give it a default, and add it to baseRow() too.

comment on table  public.sage_memory is
  'Sage''s memory bank: facts about the rider, her rolling recap, relationship counters and conversation episodes.';
comment on column public.sage_memory.mem_key is
  'Client-stable id. The app matches on this, so a row survives being edited on another device.';
comment on column public.sage_memory.record_type is
  'fact | recap | relationship | episode.';
comment on column public.sage_memory.archived_at is
  'Soft delete. Forgetting sets this rather than removing the row, so the forget propagates to other devices instead of the row simply reappearing on their next push.';
comment on column public.sage_memory.rev is
  'Bumped on every write. Sync resolves a conflict in favour of the higher rev, then the later updated_at.';
comment on column public.sage_memory.expires_at is
  'For time-bound facts — a plan for "next weekend" stops being current. Expired facts are archived by the app rather than deleted.';


-- ── 2. Indexes ───────────────────────────────────────────────────────
-- mem_key is how the app finds a row to update, so it is unique. Postgres
-- allows repeated nulls in a unique index, which is what lets the column be
-- added to an existing table without a backfill.
create unique index if not exists sage_memory_mem_key_idx
  on public.sage_memory (mem_key);

-- The read the app actually makes on boot: live rows of one kind, newest first.
create index if not exists sage_memory_type_live_idx
  on public.sage_memory (record_type, updated_at desc)
  where archived_at is null;

-- Delta pulls after the first one.
create index if not exists sage_memory_updated_idx
  on public.sage_memory (updated_at desc);


-- ── 3. Keep updated_at honest ────────────────────────────────────────
-- The app sets updated_at on every write, but a row edited from the SQL
-- editor or the Table Editor would otherwise keep a stale value and lose a
-- sync it should have won.
create or replace function public.sage_memory_touch()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end $$;

drop trigger if exists sage_memory_touch_trg on public.sage_memory;
create trigger sage_memory_touch_trg
  before update on public.sage_memory
  for each row execute function public.sage_memory_touch();


-- ── 4. Row level security ────────────────────────────────────────────
-- This project uses the anon key with no auth, matching the other tables.
-- DELETE is granted as well as UPDATE: forgetting normally archives the row
-- so the change reaches other devices, but "forget everything" genuinely
-- removes it, and leaving her memory on a server after he asked for it to be
-- wiped would be the wrong default.
alter table public.sage_memory enable row level security;

drop policy if exists "sage_memory anon read"   on public.sage_memory;
drop policy if exists "sage_memory anon insert" on public.sage_memory;
drop policy if exists "sage_memory anon update" on public.sage_memory;
drop policy if exists "sage_memory anon delete" on public.sage_memory;

create policy "sage_memory anon read"
  on public.sage_memory for select using (true);

create policy "sage_memory anon insert"
  on public.sage_memory for insert with check (true);

create policy "sage_memory anon update"
  on public.sage_memory for update using (true) with check (true);

create policy "sage_memory anon delete"
  on public.sage_memory for delete using (true);


-- ── 5. Housekeeping helper ───────────────────────────────────────────
-- Archived rows are kept for a while so a device that has been offline for a
-- fortnight still learns what was forgotten. After that they are only taking
-- up space. Call it whenever you feel like it:
--   select public.sage_memory_prune();
create or replace function public.sage_memory_prune(older_than interval default '30 days')
returns integer
language plpgsql
as $$
declare
  removed integer;
begin
  delete from public.sage_memory
   where archived_at is not null
     and archived_at < now() - older_than;
  get diagnostics removed = row_count;
  return removed;
end $$;


-- ── 6. Readable views ────────────────────────────────────────────────
-- One table holding four kinds of row is right for syncing — one migration,
-- one RLS set, one push — but it makes the Table Editor confusing: open
-- sage_memory with a single memory saved and you see two rows, because the
-- relationship counters live in there too. That reads like a duplicate and
-- is not one.
--
-- These views are the answer to "what does she actually remember". Open
-- sage_memory_facts in the Table Editor instead of the table itself.
--
-- security_invoker makes the view obey the caller's RLS rather than the
-- view owner's. Without it a view silently bypasses row level security,
-- which is the usual way a policy set gets quietly undone.

-- Just the memories. One row per thing she knows, newest first.
create or replace view public.sage_memory_facts
  with (security_invoker = true)
as
select
  id,
  mem_key,
  content      as memory,
  kind,
  topic        as subject,
  pinned,
  hits         as times_mentioned,
  confidence,
  learned_at,
  last_seen_at,
  expires_at,
  updated_at
from public.sage_memory
where record_type = 'fact'
  and archived_at is null
  and superseded_by is null
order by pinned desc, last_seen_at desc;

comment on view public.sage_memory_facts is
  'What Sage currently remembers about the rider — facts only. Excludes the relationship counters, her rolling recap, conversation episodes, and anything forgotten or superseded. This is the count the app shows as "Remembers".';

-- Everything she is holding, one row per record type, so the makeup of the
-- table is legible at a glance.
create or replace view public.sage_memory_summary
  with (security_invoker = true)
as
select
  record_type,
  count(*) filter (where archived_at is null)     as live,
  count(*) filter (where archived_at is not null) as forgotten,
  max(updated_at)                                 as last_written
from public.sage_memory
group by record_type
order by record_type;

comment on view public.sage_memory_summary is
  'Row counts per record_type. Expect exactly one relationship row and at most one recap row, however many memories there are.';
