-- ════════════════════════════════════════════════════════════
-- SpinLog — vehicle_cover
-- Task 2: move insurance / cover expiry dates out of hardcoded HTML
-- and into the database.
--
-- Run this once in the Supabase SQL editor:
--   Dashboard → SQL Editor → New query → paste → Run
--
-- Until it is run, the app falls back to localStorage and then to the
-- data-due values in index.html, so nothing breaks in the meantime.
-- ════════════════════════════════════════════════════════════

create table if not exists public.vehicle_cover (
  id          bigint generated by default as identity primary key,
  cover_type  text not null unique,
  label       text not null,
  expiry_date date not null,
  notes       text,
  updated_at  timestamptz not null default now()
);

-- cover_type is the stable machine key (a slug of the label). The app matches
-- cards on this, so the visible label can be reworded without losing the row.
create index if not exists vehicle_cover_cover_type_idx
  on public.vehicle_cover (cover_type);

-- This project uses the anon key with no auth, matching the other tables.
alter table public.vehicle_cover enable row level security;

drop policy if exists "vehicle_cover anon read"   on public.vehicle_cover;
drop policy if exists "vehicle_cover anon insert" on public.vehicle_cover;
drop policy if exists "vehicle_cover anon update" on public.vehicle_cover;

create policy "vehicle_cover anon read"
  on public.vehicle_cover for select using (true);

create policy "vehicle_cover anon insert"
  on public.vehicle_cover for insert with check (true);

create policy "vehicle_cover anon update"
  on public.vehicle_cover for update using (true) with check (true);

-- Seed the two covers the app ships with. The app also self-seeds from
-- whatever is on the cards, so this is belt-and-braces.
insert into public.vehicle_cover (cover_type, label, expiry_date)
values
  ('own-damage-cover', 'Own Damage Cover', '2026-06-24'),
  ('liability-cover',  'Liability Cover',  '2030-06-24')
on conflict (cover_type) do nothing;
